version: '3.8'

services:
  go-api:
    build: ./go-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_API_URL=http://node-api:3000
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  node-api:
    build: ./node-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GO_API_URL=http://go-api:8080
    depends_on:
      - go-api
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  angular-frontend:
    build: ./angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - node-api
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  matrix-network:
    driver: bridge
